### PR TITLE
added baidu passive subdomains search

### PR DESCRIPTION
**Pull request by Mzack9999**
- Added better fix to Dockerfile (Issue #20)
```
$ docker build . -t subfinder
Sending build context to Docker daemon  5.536MB
Step 1/7 : FROM iron/go:dev
dev: Pulling from iron/go
2595db787577: Pull complete 
25f4744d75f7: Pull complete 
e5c42b04f34b: Pull complete 
2c16999b2da4: Pull complete 
f07ddaf6c162: Pull complete 
bfac150e9ba1: Pull complete 
7c7bda04128a: Pull complete 
Digest: sha256:b80fdc916aec2ab0237bb434b0d9b022f8aabd8e161a7015aea496a90039ae1e
Status: Downloaded newer image for iron/go:dev
 ---> 04f0f1a5b78c
Step 2/7 : WORKDIR /app
Removing intermediate container e9df2f1146e5
 ---> 5ced78dfc061
Step 3/7 : ENV SRC_DIR=/go/src/github.com/Ice3man543/subfinder/
 ---> Running in 49b89c52e464
Removing intermediate container 49b89c52e464
 ---> 4e136a190682
Step 4/7 : ADD . $SRC_DIR
 ---> 56e96aae3798
Step 5/7 : RUN cd $SRC_DIR; go build -o main; cp main /app/
 ---> Running in 63dbbc36fbf8
Removing intermediate container 63dbbc36fbf8
 ---> dc0416cef305
Step 6/7 : ENTRYPOINT ["./main"]
 ---> Running in 923121ff69f2
Removing intermediate container 923121ff69f2
 ---> 5114620c981e
Step 7/7 : CMD ["-h"]
 ---> Running in c9896463ae25
Removing intermediate container c9896463ae25
 ---> 60234d343934
Successfully built 60234d343934
Successfully tagged subfinder:latest
$ 
```

- Added Baidu passive search (Issue #8)
```
$ docker run -it subfinder -d example.com -sources baidu -v

[NOTE] Edit /root/.config/subfinder/config.json with your options !
   ____     __   _____         __       
  / __/_ __/ /  / __(_)__  ___/ /__ ____
 _\ \/ // / _ \/ _// / _ \/ _  / -_) __/
/___/\_,_/_.__/_/ /_/_//_/\_,_/\__/_/   
                                      

SubFinder v0.1.0 	  Made with ❤ by @Ice3man
==================================================

baidu
[-] Searching For Subdomains in Baidu
[Baidu] www.example.com
[Baidu] mail.example.com
[Baidu] gitlab.example.com

[#] Total 3 Unique subdomains found passively

gitlab.example.com
mail.example.com
www.example.com
$
```

### CODE REVIEW

**Comment by Mzack9999** [comment]
Actually that's the best promising project about subdomains enumeration. I wanted to revamp sublist3r, but the code is a bit messy and apparently abandoned. I'm glad to help :)

**Comment by Ice3man543** [comment]
It works fine without timeout stuff. Should we remove it @Mzack9999 ?

**Comment by Mzack9999** [comment]
If by timeout you mean the following line:

```
time.Sleep(time.Duration((3 +rand.Intn(5))) * time.Second)
```

this is just a deelay added between requests to avoid eventual blocking by baidu engine.
Otherwise the timeout parameter is required by the helper function GetHTTPResponse.

**Comment by Ice3man543** [comment]
Ok. I will merge it. Thanks a lot !

**Pull request merged**
