### PR TITLE
added ask search engine

### PR DESCRIPTION
**Pull request by Mzack9999**
Implement Issue #7

### CODE REVIEW

**Comment by Ice3man543** [comment]
Thanks a lot @Mzack9999 for this. Will look into it in 4-5 hours when I am free. Do you want me to add you as a collaborator? You are doing great work. Keep it up.

**Comment by Mzack9999** [comment]
Sure, feel free to add me

**Comment by Ice3man543** [comment]
This gives me 18 results for google.com. Is that fine @Mzack9999 @codingo

**Comment by Ice3man543** [comment]
Done. Added you as a collaborator :+1: !

**Comment by Mzack9999** [comment]
I think it behaves as expected (for example sublist3er gives zero results), in order to get more results probably a configurable parameter defining the minimum recursion level should be considered? The crawler stops after a minimum of 15 (for now it's hardcoded) if no new results are found

**Comment by Ice3man543** [comment]
Thanks a lot. Will merge this once I return. I will add a --set-settings AskMinimum flag so that it can be configured. I will do something similar for all the awesome search engines you have added. :+1:

**Comment by Ice3man543** [comment]
Added --set-config AskPages=100 flags in commit 98518d5782be09cd54b0a9e5fe2e38f5f4de9391
:+1:

**Pull request merged**
